import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Circle, Clock3, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { createTodo, deleteTodo, getTodos, updateTodo, type Todo } from '@/api/todo.api';
import { getApiErrorMessage } from '@/lib/format';
import PageHeader from '@/components/PageHeader';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

const localIso = (value:string) => value ? `${value}:00` : null;
export default function TodoPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey:['todos'], queryFn:getTodos });
  const [title,setTitle] = useState(''); const [dueAt,setDueAt] = useState(''); const [priority,setPriority] = useState<Todo['priority']>('MEDIUM'); const [filter,setFilter] = useState<'ALL'|'OPEN'|'DONE'>('ALL');
  const mutation = useMutation({ mutationFn:createTodo, onSuccess:()=>{ setTitle(''); setDueAt(''); void client.invalidateQueries({queryKey:['todos']}); toast.success('Đã thêm công việc'); }, onError:e=>toast.error(getApiErrorMessage(e,'Không thể thêm công việc')) });
  const toggle = useMutation({ mutationFn:({todo,status}:{todo:Todo;status:Todo['status']})=>updateTodo(todo.id,{title:todo.title,description:todo.description??'',priority:todo.priority,status,dueAt:todo.dueAt,reminderAt:todo.reminderAt,reminderEnabled:todo.reminderEnabled}), onSuccess:()=>void client.invalidateQueries({queryKey:['todos']}) });
  const remove = useMutation({ mutationFn:deleteTodo, onSuccess:()=>{ void client.invalidateQueries({queryKey:['todos']}); toast.success('Đã xóa công việc'); } });
  const todos = useMemo(()=> (query.data??[]).filter(item=>filter==='ALL'||(filter==='DONE'?item.status==='DONE':item.status!=='DONE')), [query.data,filter]);
  return <div className="space-y-6"><PageHeader title="Việc cần làm" description="Một nơi gọn gàng để giữ nhịp công việc, hạn chót và lời nhắc của bạn." />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]">
      <Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Danh sách hôm nay</CardTitle><div className="flex gap-1 rounded-xl bg-muted p-1">{(['ALL','OPEN','DONE'] as const).map(value=><button key={value} onClick={()=>setFilter(value)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${filter===value?'bg-background shadow-sm':'text-muted-foreground'}`}>{value==='ALL'?'Tất cả':value==='OPEN'?'Đang làm':'Đã xong'}</button>)}</div></div></CardHeader><CardContent className="space-y-3">{query.isLoading?<p className="py-10 text-center text-sm text-muted-foreground">Đang tải công việc...</p>:todos.length===0?<div className="rounded-2xl border border-dashed p-8 text-center"><Circle className="mx-auto size-8 text-muted-foreground/40"/><p className="mt-3 font-medium">Chưa có việc nào trong bộ lọc này</p><p className="mt-1 text-sm text-muted-foreground">Tạo việc đầu tiên ở khung bên cạnh.</p></div>:todos.map(todo=><div key={todo.id} className={`flex items-start gap-3 rounded-2xl border p-4 transition ${todo.status==='DONE'?'bg-muted/50 opacity-70':'bg-card hover:border-emerald-200 hover:shadow-sm'}`}><button className="mt-0.5 rounded-full text-emerald-600" onClick={()=>toggle.mutate({todo,status:todo.status==='DONE'?'OPEN':'DONE'})} aria-label="Đánh dấu hoàn thành">{todo.status==='DONE'?<Check className="size-5"/>:<Circle className="size-5"/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`font-medium ${todo.status==='DONE'?'line-through':''}`}>{todo.title}</p><Badge variant={todo.priority==='HIGH'?'destructive':'secondary'}>{todo.priority==='HIGH'?'Ưu tiên cao':todo.priority==='LOW'?'Thấp':'Trung bình'}</Badge></div>{todo.description&&<p className="mt-1 text-sm text-muted-foreground">{todo.description}</p>}{todo.dueAt&&<p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3.5"/> Hạn {formatDate(todo.dueAt)}</p>}</div><button className="rounded-lg p-2 text-muted-foreground hover:bg-red-50 hover:text-red-600" onClick={()=>remove.mutate(todo.id)} aria-label="Xóa công việc"><Trash2 className="size-4"/></button></div>)}</CardContent></Card>
      <Card className="h-fit border-emerald-200 bg-gradient-to-b from-emerald-50/80 to-background"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-emerald-700"/> Thêm công việc</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-1.5"><Label htmlFor="todo-title">Tên công việc</Label><Input id="todo-title" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Chuẩn bị báo cáo tuần"/></div><div className="space-y-1.5"><Label htmlFor="todo-due">Hạn hoàn thành</Label><Input id="todo-due" type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></div><div className="space-y-1.5"><Label>Độ ưu tiên</Label><select value={priority} onChange={e=>setPriority(e.target.value as Todo['priority'])} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="HIGH">Cao</option><option value="MEDIUM">Trung bình</option><option value="LOW">Thấp</option></select></div><Button className="w-full" disabled={!title.trim()||mutation.isPending} onClick={()=>mutation.mutate({title:title.trim(),priority,status:'OPEN',dueAt:localIso(dueAt)})}>{mutation.isPending?'Đang thêm...':'Tạo công việc'}</Button></CardContent></Card>
    </div></div>;
}
function formatDate(value:string){return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
