import api from "./axios";

export type JournalCategory = "OBSERVATION" | "SELF" | "MEMORY" | "IMAGINATION" | "REFLECTION" | "RELATIONSHIP" | "FUTURE" | "QUIRKY";
export type JournalDepth = "LIGHT" | "MEDIUM" | "DEEP";
export type JournalOrigin = "PROMPT" | "FREEFORM";
export type JournalMood = "VERY_LOW" | "LOW" | "NEUTRAL" | "GOOD" | "VERY_GOOD";
export type JournalPack = { id:string;name:string;description:string|null;icon:string|null;followed:boolean;promptCount:number };
export type JournalPrompt = { id: string; content: string; category: JournalCategory; depth: JournalDepth; active: boolean; pack: JournalPack|null };
export type JournalEntry = { id: string; entryDate: string; origin: JournalOrigin; prompt: JournalPrompt | null; title: string | null; body: string; mood: JournalMood | null; tags:string[];imageUrls:string[]; createdAt: string; updatedAt: string };
export type JournalToday = { date: string; prompt: JournalPrompt; answered: boolean; entry: JournalEntry | null };
export type JournalEntryInput = { origin: JournalOrigin; promptId?: string | null; entryDate?: string; title?: string; body: string; mood?: JournalMood | null;tags?:string[];imageUrls?:string[] };
export type JournalSettings = { reminderEnabled: boolean; reminderTime: string;personalizedPromptsEnabled:boolean;aiFollowUpEnabled:boolean;lockEnabled:boolean };
export type JournalStats={writtenDays:number;entryCount:number;moodDays:{date:string;mood:JournalMood}[]};
export type PageResponse<T> = { content: T[]; page: number; size: number; totalElements: number; totalPages: number; first: boolean; last: boolean };

export const getJournalToday = async () => (await api.get<JournalToday>("/journal/today")).data;
export const skipJournalPrompt = async () => (await api.post<JournalToday>("/journal/today/skip")).data;
export const switchJournalDepth = async (depth:JournalDepth) => (await api.post<JournalToday>(`/journal/today/depth/${depth}`)).data;
export const getJournalEntries = async (params: Record<string, string | number | undefined>) => (await api.get<PageResponse<JournalEntry>>("/journal/entries", { params })).data;
export const createJournalEntry = async (payload: JournalEntryInput) => (await api.post<JournalEntry>("/journal/entries", payload)).data;
export const updateJournalEntry = async (id: string, payload: JournalEntryInput) => (await api.put<JournalEntry>(`/journal/entries/${id}`, payload)).data;
export const deleteJournalEntry = async (id: string) => { await api.delete(`/journal/entries/${id}`); };
export const getJournalPrompts = async (params: Record<string, string | number | undefined>) => (await api.get<PageResponse<JournalPrompt>>("/journal/prompts", { params })).data;
export const getJournalSettings = async () => (await api.get<JournalSettings>("/journal/settings")).data;
export const updateJournalSettings = async (payload: JournalSettings) => (await api.put<JournalSettings>("/journal/settings", payload)).data;
export const getJournalOnThisDay=async()=>(await api.get<JournalEntry[]>("/journal/on-this-day")).data;
export const getJournalStats=async(month:string)=>(await api.get<JournalStats>("/journal/stats",{params:{month}})).data;
export const getJournalTags=async()=>(await api.get<string[]>("/journal/tags")).data;
export const getJournalPacks=async()=>(await api.get<JournalPack[]>("/journal/packs")).data;
export const followJournalPack=async(id:string,follow:boolean)=>(await (follow?api.put<JournalPack>(`/journal/packs/${id}/follow`):api.delete<JournalPack>(`/journal/packs/${id}/follow`))).data;
export const getPersonalizedJournalPrompt=async()=>(await api.get<{question:string}>("/journal/ai/personalized-prompt")).data;
export const getJournalFollowUp=async(body:string)=>(await api.post<{question:string}>("/journal/ai/follow-up",{body})).data;
export const getJournalLockStatus=async()=>(await api.get<JournalSettings>("/journal/lock/status")).data;
export const unlockJournal=async(pin:string)=>{const data=(await api.post<{unlockToken:string;expiresAt:string}>("/journal/lock/unlock",{pin})).data;sessionStorage.setItem("fittrack-journal-unlock",data.unlockToken);return data;};
export const setJournalPin=async(pin:string)=>(await api.put<JournalSettings>("/journal/lock/pin",{pin})).data;
export const disableJournalPin=async(pin:string)=>(await api.delete<JournalSettings>("/journal/lock/pin",{data:{pin}})).data;
export const downloadJournalMarkdown=async()=>{const blob=(await api.get<Blob>("/journal/export/markdown",{responseType:"blob"})).data;const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="fittrack-journal.md";a.click();URL.revokeObjectURL(url);};
export const printJournalPdf=async()=>{const w=window.open("","_blank");if(!w)throw new Error("POPUP_BLOCKED");try{w.document.write("<p>Đang chuẩn bị bản in Nhật ký...</p>");const html=(await api.get<string>("/journal/export/print",{responseType:"text"})).data;w.document.open();w.document.write(html);w.document.close();}catch(error){w.close();throw error;}};

export const getAdminJournalPrompts = async (params: Record<string, string | number | boolean | undefined>) => (await api.get<PageResponse<JournalPrompt>>("/admin/journal/prompts", { params })).data;
export type AdminJournalPromptInput={content:string;category:JournalCategory;depth:JournalDepth;active:boolean;packId?:string|null};
export const createAdminJournalPrompt = async (payload: AdminJournalPromptInput) => (await api.post<JournalPrompt>("/admin/journal/prompts", payload)).data;
export const updateAdminJournalPrompt = async (id: string, payload: AdminJournalPromptInput) => (await api.put<JournalPrompt>(`/admin/journal/prompts/${id}`, payload)).data;
export type AdminJournalPack={id:string;name:string;description:string|null;icon:string|null;active:boolean;sortOrder:number;promptCount:number};
export type AdminJournalPackInput={name:string;description?:string;icon?:string;active:boolean;sortOrder:number};
export const getAdminJournalPacks=async()=>(await api.get<AdminJournalPack[]>("/admin/journal/prompts/packs")).data;
export const createAdminJournalPack=async(payload:AdminJournalPackInput)=>(await api.post<AdminJournalPack>("/admin/journal/prompts/packs",payload)).data;
export const updateAdminJournalPack=async(id:string,payload:AdminJournalPackInput)=>(await api.put<AdminJournalPack>(`/admin/journal/prompts/packs/${id}`,payload)).data;
export const archiveAdminJournalPack=async(id:string)=>{await api.delete(`/admin/journal/prompts/packs/${id}`);};
